# Dependencies
markdown:         redcarpet
highlighter:      pygments

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Permalinks
permalink:        /:categories/:title
relative_permalinks: true

# Setup
title:            Ionic by Request
tagline:          'Developing mobile application with technologies you already know and love.'
description:      'Developing mobile application with technologies you already know and love. <br>Made by <a href="https://twitter.com/paulo_gr" target="_blank">@paulo_gr</a>'
url:              http://www.ionicbyrequest.com
baseurl:          /

author:
  name:           'Paulo Rodrigues'
  url:            https://twitter.com/paulo_gr

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/paulogr
