# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ionic by Request
tagline:          'Developing mobile application with technologies you already know and love.'
description:      'Developing mobile application with technologies you already know and love. <br>Made by <a href="https://twitter.com/paulogr" target="_blank">@paulogr</a>'
url:              http://www.ionicbyrequest.com
baseurl:          /ionicbyrequest

author:
  name:           'Paulo Rodrigues'
  url:            https://twitter.com/paulogr

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/paulogr
